"""remove_background_field_from_agent_tables

Revision ID: 036715f17833
Revises: cddcb44b483d
Create Date: 2025-10-24 22:51:06.644970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036715f17833'
down_revision: Union[str, None] = 'cddcb44b483d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_agents', 'background')
    op.drop_column('template_agent_snapshots', 'background')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_agent_snapshots', sa.Column('background', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config_agents', sa.Column('background', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
