"""add_config_snapshots_table

Revision ID: 35786a210175
Revises: 609a95e27d46
Create Date: 2025-09-24 00:03:10.340032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35786a210175'
down_revision: Union[str, None] = '609a95e27d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('config_snapshots_unique_version', 'config_snapshots', ['config_id', 'version_number'], unique=True)
    op.create_index(op.f('ix_config_snapshots_config_id'), 'config_snapshots', ['config_id'], unique=False)
    op.add_column('runs', sa.Column('config_snapshot_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'runs', 'config_snapshots', ['config_snapshot_id'], ['id'])
    op.drop_column('runs', 'config_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_column('runs', 'config_snapshot_id')
    op.drop_index(op.f('ix_config_snapshots_config_id'), table_name='config_snapshots')
    op.drop_index('config_snapshots_unique_version', table_name='config_snapshots')
    op.drop_table('config_snapshots')
    # ### end Alembic commands ###
