"""new models for interventions, tools, documents and embeddings

Revision ID: 9c796569ae4c
Revises: 67317cf3668e
Create Date: 2025-10-23 21:51:29.249534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c796569ae4c'
down_revision: Union[str, None] = '67317cf3668e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
