"""add tables for persistent documents and their dynamic referencing accross runs and agents. add support for chunks in embeddings table

Revision ID: b78b6328cb20
Revises: 036715f17833
Create Date: 2025-10-31 03:18:46.315244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78b6328cb20'
down_revision: Union[str, None] = '036715f17833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.add_column('embeddings', sa.Column('chunk_start', sa.Integer(), nullable=True))
    op.add_column('embeddings', sa.Column('chunk_end', sa.Integer(), nullable=True))
    op.alter_column('embeddings', 'run_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('embeddings_chunk_lookup', 'embeddings', ['source_type', 'source_id', 'chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('embeddings_chunk_lookup', table_name='embeddings')
    op.alter_column('embeddings', 'run_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('embeddings', 'chunk_end')
    op.drop_column('embeddings', 'chunk_start')
    op.drop_column('embeddings', 'chunk_index')
    # ### end Alembic commands ###
